source 'https://rubygems.org'

# Pin Ruby & CocoaPods to a known-good combo.
# Ruby 4.x has a String/ASCII-8BIT regression that breaks `pod install` paths
# (Encoding::CompatibilityError in Pod::Config#installation_root). Stay on
# Ruby 3.3 LTS until CocoaPods 1.17+ ships a fix.
ruby ">= 3.3.0"

gem 'cocoapods', '~> 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
