// 法務正本 (document/legal/<doc>/<locale>.md) を単一ソースとして、
// アプリ同梱用の HTML + ハッシュに変換し src/content/legalDocs.generated.ts を生成する。
//
//   node scripts/gen-legal.mjs
//
// 方針:
//   • 正本は document/legal/ の md (= 唯一の source of truth)。本ファイルは生成物。
//   • アプリは WebView で html を表示 (= オフライン可、ネット/Vercel 非依存)。
//   • 各文書の SHA-256 を記録 (= consent-log-spec の「正本の版+ハッシュ」要件に対応)。
//   • md の限定サブセット (見出し/太字/inline code/箇条書き/引用/表/リンク) を変換。

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LEGAL_DIR = join(__dirname, '../../document/legal');
const OUT = join(__dirname, '../src/content/legalDocs.generated.ts');

// アプリで表示する対ユーザー文書のみ (consent-log-spec 等の社内文書は対象外)。
// tester-consent は 2026-07-06 に terms-of-service へ置換 (= 正本 md は証跡照合用に残置、 同梱はしない)。
const DOCS = ['terms-of-service', 'privacy-policy'];
const LOCALES = ['ja', 'en'];

// ─── md → html (限定サブセット) ─────────────────────────────────────

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function inline(s) {
  let t = escapeHtml(s);
  t = t.replace(/`([^`]+)`/g, '<code>$1</code>');
  t = t.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  // 相対リンク等はアプリ内で解決できないのでラベルのみ残す
  t = t.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1');
  return t;
}

function renderBlocks(lines) {
  const out = [];
  let i = 0;
  const isBlank = (l) => l.trim() === '';

  while (i < lines.length) {
    const line = lines[i];

    if (isBlank(line)) { i++; continue; }

    // 見出し
    const h = line.match(/^(#{1,6})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      out.push(`<h${level}>${inline(h[2].trim())}</h${level}>`);
      i++;
      continue;
    }

    // 水平線
    if (/^-{3,}$/.test(line.trim())) { out.push('<hr/>'); i++; continue; }

    // 表 (連続する | 行)
    if (line.trim().startsWith('|')) {
      const rows = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) { rows.push(lines[i].trim()); i++; }
      const cells = (r) => r.replace(/^\|/, '').replace(/\|$/, '').split('|').map((c) => c.trim());
      const isSep = (r) => /^\|?[\s:|-]+\|?$/.test(r) && r.includes('-');
      let html = '<table>';
      rows.forEach((r, idx) => {
        if (idx === 1 && isSep(r)) return;
        const tag = idx === 0 ? 'th' : 'td';
        html += '<tr>' + cells(r).map((c) => `<${tag}>${inline(c)}</${tag}>`).join('') + '</tr>';
      });
      html += '</table>';
      out.push(html);
      continue;
    }

    // 引用 (連続する > 行) → 中身を再帰描画
    if (line.trim().startsWith('>')) {
      const inner = [];
      while (i < lines.length && lines[i].trim().startsWith('>')) {
        inner.push(lines[i].replace(/^\s*>\s?/, ''));
        i++;
      }
      out.push(`<blockquote>${renderBlocks(inner)}</blockquote>`);
      continue;
    }

    // 箇条書き (連続する - / * 行)
    if (/^\s*[-*]\s+/.test(line)) {
      const items = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        items.push(`<li>${inline(lines[i].replace(/^\s*[-*]\s+/, ''))}</li>`);
        i++;
      }
      out.push(`<ul>${items.join('')}</ul>`);
      continue;
    }

    // 番号リスト (連続する "N." 行)。 グループ間で番号が続く場合に備えて start を保持する
    if (/^\s*\d+[.)]\s+/.test(line)) {
      const start = Number(line.match(/^\s*(\d+)[.)]/)[1]);
      const items = [];
      while (i < lines.length && /^\s*\d+[.)]\s+/.test(lines[i])) {
        items.push(`<li>${inline(lines[i].replace(/^\s*\d+[.)]\s+/, ''))}</li>`);
        i++;
      }
      out.push(`<ol${start === 1 ? '' : ` start="${start}"`}>${items.join('')}</ol>`);
      continue;
    }

    // 段落 (空行 or 特殊行まで連結)
    const para = [];
    while (
      i < lines.length &&
      !isBlank(lines[i]) &&
      !/^(#{1,6})\s/.test(lines[i]) &&
      !lines[i].trim().startsWith('|') &&
      !lines[i].trim().startsWith('>') &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !/^\s*\d+[.)]\s+/.test(lines[i]) &&
      !/^-{3,}$/.test(lines[i].trim())
    ) {
      para.push(lines[i].trim());
      i++;
    }
    out.push(`<p>${inline(para.join(' '))}</p>`);
  }

  return out.join('');
}

function mdToHtml(md) {
  return renderBlocks(md.replace(/\r\n/g, '\n').split('\n'));
}

function title(md) {
  const m = md.match(/^#\s+(.*)$/m);
  return m ? m[1].replace(/\s*\([^)]*\)\s*$/, '').trim() : '';
}

// ─── 生成 ──────────────────────────────────────────────────────────

const result = {};
for (const locale of LOCALES) {
  result[locale] = {};
  for (const doc of DOCS) {
    const path = join(LEGAL_DIR, doc, `${locale}.md`);
    const md = readFileSync(path, 'utf8');
    const hash = createHash('sha256').update(md, 'utf8').digest('hex');
    result[locale][doc] = { title: title(md), hash, html: mdToHtml(md) };
  }
}

const banner =
  '// AUTO-GENERATED by scripts/gen-legal.mjs — DO NOT EDIT.\n' +
  '// Source of truth: document/legal/<doc>/<locale>.md\n' +
  '// Regenerate: npm run gen:legal\n\n';

const body =
  banner +
  `export type LegalDocKey = ${DOCS.map((d) => `'${d}'`).join(' | ')};\n\n` +
  'export interface LegalDocContent {\n' +
  '  /** 正本 md の最初の見出し */\n  title: string;\n' +
  '  /** 正本 md (raw) の SHA-256。consent-log の「版+ハッシュ」に使う */\n  hash: string;\n' +
  '  /** md から生成した本文 HTML (WebView で表示) */\n  html: string;\n}\n\n' +
  `export const legalDocs: Record<'ja' | 'en', Record<LegalDocKey, LegalDocContent>> = ${JSON.stringify(result, null, 2)};\n\n` +
  "export function getLegalDoc(locale: 'ja' | 'en', key: LegalDocKey): LegalDocContent {\n" +
  '  return (legalDocs[locale] ?? legalDocs.ja)[key];\n}\n';

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body, 'utf8');

const n = LOCALES.length * DOCS.length;
console.log(`generated ${OUT} (${n} docs)`);
for (const doc of DOCS) {
  console.log(`  ${doc}: ja=${result.ja[doc].hash.slice(0, 12)}… en=${result.en[doc].hash.slice(0, 12)}…`);
}
